added functional tests for the charm.
canonical/charm-software-inventory-exporter pull request #6
Opened 2023-03-22 01:43 UTC by gabrielcocenza

- removed installation as classic

2023-03-22 07:50 UTC, esunar reviewed
recheck

2023-03-22 08:06 UTC, chanchiwai-ray approved these changes, later dismissed
LGTM, (non-blocking) it seems that there are 3 independent PRs packed in this PR, it would be nicer to have 3 small PRs (or at least 3 commits).

- apply bootstack template (`.gitignore`, `tox.ini`)
- add basic functional tests (`tests/*`)
- fix unit tests (`src/charm.py`, `unit/test_charm.py`)

2023-03-22 08:20 UTC, esunar approved these changes

2023-03-22 09:45 UTC, mkalcok requested changes
Overall this change is fine, but the inclusion of snap as a local resource is a blocker. We have to wait until it's published in the snapstore.

2023-03-22 09:45 UTC, mkalcok commented on src/charm.py
> +        return cache[self.EXPORTER_SNAP_NAME]
Why was this change needed?

2023-03-22 09:45 UTC, mkalcok commented on tests/functional/tests/bundles/resources/software-inventory-exporter.snap
It's not a good idea to merge 31MB of binary data to the repository as it's gonna stay there forever. These functional tests will have to wait until the snap is published in the store before we can merge it.

2023-03-22 09:45 UTC, mkalcok commented on tests/functional/tests/bundles/overlays/local-charm-overlay.yaml.j2
> +      exporter-snap: "resources/software-inventory-exporter.snap"
It's fine to use local resource for development of tests before the snap is in the store, but it can't be pushed to the main repo and used in CI.

2023-03-22 09:45 UTC, mkalcok commented on tests/functional/tests/test_charm.py
> +    def validate_exporter(self):
If it's not overly complicated, I think it'd be better to also test that the endpoint provide correct data (e.g. all snaps/kernels/packages are reported by the exporter)

2023-03-22 10:14 UTC, rgildein commented on tests/functional/requirements.txt
> +requests
Can you remove unnecessary zaza requirements here? Thanks

2023-03-22 10:16 UTC, rgildein commented on tests/functional/tests/bundles/resources/software-inventory-exporter.snap
I agree w/ Martin here, we can pull code a build snap if that is really needed, but it's ok to wait until snap is not released.

2023-03-22 12:16 UTC, esunar requested changes

2023-05-08 15:17 UTC, rgildein approved these changes, later dismissed
The changes look good to me, but I think this is a good example of a PR that should be split into two PRs. Can you please update description in PR, thanks.

2023-05-08 19:48 UTC, esunar approved these changes, later dismissed
Approved with a nice to have inline comment.

2023-05-09 06:43 UTC, rgildein approved these changes

2023-05-09 12:20 UTC, esunar approved these changes

2023-05-09 12:20 UTC, esunar approved these changes

2023-05-09 12:20 UTC, esunar approved these changes

2023-05-09 12:20 UTC, esunar approved these changes

2023-05-09 12:20 UTC, esunar approved these changes

2023-05-09 12:20 UTC, esunar approved these changes

2023-05-09 12:28 UTC, merged